### ISSUE TITLE
New version question

### ISSUE THREAD

**Issue by bb1075** [zugmana/xnat-access#1]
Hi Andre - I am trying your "Issue" message board you mentioned this morning! Thanks for all your work on this!
I am getting this message with the updated version (0.2.1) - can you check this traceback?  after this runs, the data is not in the output directory.
(XNAT) bash-4.2$ xnat-access -i **[edited]** -o testing -d **[edited]** --keepdicom --search_name
.netrc file not found. Prompting for username and password
current user is bbenson
Please enter Password : 
WARNING : tempfile not specified by user. Please consider setting your TMP path before running this script
Please type : TMP=/home/bbenson/tmp or some other approapriate path.
using system default may cause problems
Will try /home/bbenson/tmp
working on dicoms. Please do not interrupt.
Downloading by Name
Matching XNAT entry by name
please check data carefully
found subject
 15.5 MiB |                   #                                                         |   7.9 MiB/s
Traceback (most recent call last):
  File "/home/bbenson/conda/envs/XNAT/bin/sortme", line 8, in <module>
    sys.exit(main())
  File "/home/bbenson/conda/envs/XNAT/lib/python3.9/site-packages/downloadtools/sortme.py", line 256, in main
    sortMultiEcho(allFileNames,way)
  File "/home/bbenson/conda/envs/XNAT/lib/python3.9/site-packages/downloadtools/sortme.py", line 101, in sortMultiEcho
    nRepetitions = int      (returnTagValue(dicomHdr, ('0020','0105')))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
 13.7 MiB |                    #                                                        |   6.8 MiB/s
EPI-opposite-blip-PE-for-distortion-correction_3 is not multiECHO
 13.7 MiB |                 #                                                           |   7.9 MiB/s
EPI-matching-blip-for-distortion-correction_4 is not multiECHO
 24.9 MiB |                                  #                                          |   7.5 MiB/s
Anat-T1w-MP-RAGE-1mm_5 is not multiECHO
 13.7 MiB |                 #                                                           |   7.9 MiB/s
EPI-opposite-blip-PE-for-distortion-correction_6 is not multiECHO
 13.7 MiB |                     #                                                       |   6.5 MiB/s
EPI-matching-blip-for-distortion-correction_7 is not multiECHO
 24.7 MiB |                                #                                            |   7.7 MiB/s
ORIG-Anat-T1w-MP-RAGE-1mm_40005 is not multiECHO
working on dicoms. Please do not interrupt.

**Comment by zugmana** [comment]
Hi @bb1075,

The error you are seeing is because some localizers don't have that dicom tag. 
This should not affect your download. 
I'll try to silence this in future versions, but it is not a big priority.

Cheers,
Andre

**Comment by bb1075** [comment]
OK, thanks. Not a bit deal then. But...after it finishes, there is no data in the output directory.

**Comment by zugmana** [comment]
Can you make sure you use the full path after -o
This might be about your working directory. I've downloaded some localizers into your path, and it worked.

**Comment by zugmana** [comment]
Posting this here to make other users aware of what was discussed:

#########

Yes.
There is some reason to that, makes it easier to build the bids.
The advantage of doing this is that you can have all types of data (dicoms, nifty as exported by dicom2niix, and a bids) without conflicting or all of them getting mixed up.
 
 
From: [edited]
Date: Friday, October 28, 2022 at 4:02 PM
To:[edited]
Subject: Re: Sorry to bother you with another email

OK, I can work around that. This is mostly for the backups Danny wants. I think there are a few projects still using dicoms, but any ne projects people are using nfti.
 
I also see the name is now sub-12345 – is this permanent change?
 
From: [edited]
Date: Friday, October 28, 2022 at 3:55 PM
To: [edited]
Subject: Re: Sorry to bother you with another email
 
It also won’t save anything before it’s ready to…
So if you interrupt the program prematurely you won’t end up with data that was not anonymized… Much safer.
 
 
From: [edited]
Date: Friday, October 28, 2022 at 3:52 PM
To: [edited]
Subject: Re: Sorry to bother you with another email

It’s putting in a directory called dicom inside testing – that’s new.
